### ISSUE TITLE
some compile errors encountered 

### ISSUE THREAD

**Issue by zinking** [bing-ads-sdk/BingAds-Java-SDK#1]
not sure how this was possible:

	renamed:    src/main/java/com/microsoft/bingads/internal/functionalInterfaces/BiConsumer.java -> src/main/java/com/microsoft/bingads/internal/functionalinterfaces/BiConsumer.java
	renamed:    src/main/java/com/microsoft/bingads/internal/functionalInterfaces/BiFunction.java -> src/main/java/com/microsoft/bingads/internal/functionalinterfaces/BiFunction.java
	renamed:    src/main/java/com/microsoft/bingads/internal/functionalInterfaces/Consumer.java -> src/main/java/com/microsoft/bingads/internal/functionalinterfaces/Consumer.java
	renamed:    src/main/java/com/microsoft/bingads/internal/functionalInterfaces/Function.java -> src/main/java/com/microsoft/bingads/internal/functionalinterfaces/Function.java
	renamed:    src/main/java/com/microsoft/bingads/internal/functionalInterfaces/Predicate.java -> src/main/java/com/microsoft/bingads/internal/functionalinterfaces/Predicate.java
	renamed:    src/main/java/com/microsoft/bingads/internal/functionalInterfaces/Supplier.java -> src/main/java/com/microsoft/bingads/internal/functionalinterfaces/Supplier.java
	renamed:    src/main/java/com/microsoft/bingads/internal/functionalInterfaces/TriConsumer.java -> src/main/java/com/microsoft/bingads/internal/functionalinterfaces/TriConsumer.java

diff --git a/src/test/java/com/microsoft/bingads/api/test/entities/targets/campaign/bids/daytime/BulkCampaignDayTimeTargetBidTest.java b/src/test/java/com/microsoft/bingads/api/test/entities/targindex bcd9379..ba7f9a1 100644
--- a/src/test/java/com/microsoft/bingads/api/test/entities/targets/campaign/bids/daytime/BulkCampaignDayTimeTargetBidTest.java
+++ b/src/test/java/com/microsoft/bingads/api/test/entities/targets/campaign/bids/daytime/BulkCampaignDayTimeTargetBidTest.java
@@ -1,4 +1,6 @@
-package com.microsoft.bingads.api.test.entities.target.campaign.bids.daytime;
+package com.microsoft.bingads.api.test.entities.targets.campaign.bids.daytime;

**Comment by dennis-yemelyanov** [comment]
Thanks! Fixed compilation errors.
